name: DeathSwap
author: Joshalot
main: com.github.joshuahuahua.DeathSwap.Main
version: 1.5
description: Multiplayer DeathSwap Plugin

commands:
  Deathswap:
    aliases: ds
    description: Use /ds help for more information
